# This file was auto-generated by cabal2nix. Please do NOT edit manually!

{ cabal, cabalInstall, cryptoApi, errors, HsOpenSSL, criterion, random, hspec, network
, networkSimple, QuickCheck, vector
}:

cabal.mkDerivation (self: {
  pname = "dissent";
  version = "0.0.1";
  src = ./.;
  buildDepends = [
    cryptoApi errors HsOpenSSL network networkSimple vector
  ];
  testDepends = [ cabalInstall criterion random hspec network networkSimple QuickCheck vector ];
  meta = {
    description = "Accountable group anonymity protocol";
    license = self.stdenv.lib.licenses.mit;
    platforms = self.ghc.meta.platforms;
  };
})
